export const FUNCTION_NAME = "__nlite";
export const EDGE_FUNCTION_NAME = "__nlite-edge";
export const FUNCTION_SERVER_DIR = "server";
export const NETLIFY_OUTPUT_DIR = ".netlify/v1";
export const NETLIFY_FUNCTIONS_DIR = `${NETLIFY_OUTPUT_DIR}/functions`;
export const NETLIFY_EDGE_FUNCTIONS_DIR = `${NETLIFY_OUTPUT_DIR}/edge-functions`;
export const ROOT_RSC_ALIAS = "_rsc";
export const REDIRECTS_GENERATED_MARKER = "# Generated by nlite for Netlify";
