import { createRequire } from "node:module";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Logger, Plugin, PluginOption, ResolvedConfig } from "vite";

import { RSC_POSTFIX } from "../utils/constants.js";
import { tryCatch } from "../utils/index.js";

export interface NetlifyAdapterOptions {}

const FUNCTION_NAME = "__nlite";
const DEFAULT_PUBLISH = ".nlite/client";
const FUNCTION_SERVER_DIR = "server";
const NETLIFY_FUNCTIONS_DIR = ".netlify/v1/functions";
const ROOT_RSC_ALIAS = "_rsc";
const REDIRECTS_GENERATED_MARKER = "# Generated by nlite for Netlify";

export function netlify(_options: NetlifyAdapterOptions = {}): PluginOption[] {
  let config: ResolvedConfig;

  const plugin: Plugin = {
    name: "nlite:netlify",
    apply: "build",
    enforce: "post",
    applyToEnvironment(environment) {
      return environment.name === "api";
    },
    configResolved(resolvedConfig) {
      config = resolvedConfig;
    },
    async closeBundle() {
      const root = config.root;
      const serverOutDir = path.resolve(root, config.environments.rsc.build.outDir);

      if (!(await exists(serverOutDir))) {
        config.logger.warn("[nlite] Netlify adapter skipped: server bundle was not found.");
        return;
      }

      const clientOutDir = path.resolve(root, config.environments.client.build.outDir);

      await Promise.all([
        writeNetlifyFunction(root, serverOutDir),
        writeNetlifyConfig(root),
        writeNetlifyToml(root, config.logger),
        fixRootRscAsset(clientOutDir),
      ]);

      config.logger.info(`[nlite] Netlify build ready.`);
    },
  };

  return [plugin];
}

async function fixRootRscAsset(publishDir: string) {
  const dotRscPath = path.join(publishDir, RSC_POSTFIX);

  if (!(await exists(dotRscPath))) {
    return;
  }

  await fs.rename(dotRscPath, path.join(publishDir, ROOT_RSC_ALIAS));
  await writeNetlifyRedirects(publishDir);
}

async function writeNetlifyRedirects(publishDir: string) {
  const redirectsPath = path.join(publishDir, "_redirects");
  const generated = [`${REDIRECTS_GENERATED_MARKER}`, `/.rsc /_rsc 200`, ""].join("\n");

  if (!(await exists(redirectsPath))) {
    await fs.writeFile(redirectsPath, generated);
    return;
  }

  const existing = await fs.readFile(redirectsPath, "utf8");
  const withoutGenerated = stripGeneratedRedirectsSection(existing);

  await fs.writeFile(
    redirectsPath,
    withoutGenerated ? `${withoutGenerated.trimEnd()}\n\n${generated}` : generated,
  );
}

function stripGeneratedRedirectsSection(content: string) {
  const markerIndex = content.indexOf(REDIRECTS_GENERATED_MARKER);

  if (markerIndex === -1) {
    return content;
  }

  return content.slice(0, markerIndex).trimEnd();
}

async function writeNetlifyFunction(root: string, serverOutDir: string) {
  const functionsDir = path.join(root, NETLIFY_FUNCTIONS_DIR);
  const functionDir = path.join(functionsDir, FUNCTION_NAME);
  const functionPath = path.join(functionDir, "index.js");
  const serverImportPath = `./${FUNCTION_SERVER_DIR}/index.js`;

  await fs.rm(functionsDir, { recursive: true, force: true });
  await fs.mkdir(functionDir, { recursive: true });
  await copyDir(serverOutDir, path.join(functionDir, FUNCTION_SERVER_DIR));
  await fs.writeFile(
    functionPath,
    `${buildFunctionSource(serverImportPath, getGeneratorString())}\n`,
  );
}

function buildFunctionSource(serverImportPath: string, generator: string) {
  return `import { handler } from "${serverImportPath}";

const ASSETS = {
  fetch(request) {
    return fetch(request);
  },
};

export default async (request, _env) => handler(request, { ..._env, ASSETS });

export const config = {
  name: "nlite server",
  generator: ${JSON.stringify(generator)},
  path: "/*",
  excludedPath: "/.netlify/*",
  preferStatic: true,
  includedFiles: [${JSON.stringify(`${NETLIFY_FUNCTIONS_DIR}/${FUNCTION_NAME}/**`)}],
};
`;
}

async function writeNetlifyConfig(root: string) {
  const configPath = path.join(root, ".netlify/v1/config.json");

  await fs.mkdir(path.dirname(configPath), { recursive: true });
  await fs.writeFile(
    configPath,
    `${JSON.stringify(
      {
        functions: {
          directory: NETLIFY_FUNCTIONS_DIR,
          included_files: [`${NETLIFY_FUNCTIONS_DIR}/${FUNCTION_NAME}/**`],
        },
      },
      null,
      2,
    )}\n`,
  );
}

async function copyDir(source: string, destination: string) {
  if (!(await exists(source))) {
    return;
  }

  await fs.rm(destination, { recursive: true, force: true });
  await fs.cp(source, destination, { recursive: true, force: true });
}

async function writeNetlifyToml(root: string, logger: Logger) {
  const tomlPath = path.join(root, "netlify.toml");

  if (await exists(tomlPath)) {
    const content = await fs.readFile(tomlPath, "utf8");
    const {
      content: updated,
      changed,
      previousPublish,
    } = mergeNetlifyTomlPublish(content, DEFAULT_PUBLISH);

    if (!changed) {
      return;
    }

    if (previousPublish && previousPublish !== DEFAULT_PUBLISH) {
      logger.info(
        `[nlite] Updated netlify.toml [build].publish from "${previousPublish}" to "${DEFAULT_PUBLISH}".`,
      );
    }

    await fs.writeFile(tomlPath, updated.endsWith("\n") ? updated : `${updated}\n`);
    return;
  }

  await fs.writeFile(tomlPath, `[build]\n  publish = ${JSON.stringify(DEFAULT_PUBLISH)}\n`);
  logger.info(`[nlite] Created netlify.toml with publish directory "${DEFAULT_PUBLISH}".`);
}

function mergeNetlifyTomlPublish(content: string, publish: string) {
  const lines = content.split(/\r?\n/);
  const buildIndex = lines.findIndex((line) => /^\s*\[build\]\s*(?:#.*)?$/.test(line));

  if (buildIndex === -1) {
    const separator =
      content.length > 0 && !content.endsWith("\n\n")
        ? content.endsWith("\n")
          ? "\n"
          : "\n\n"
        : "";
    return {
      content: `${content}${separator}[build]\n  publish = ${JSON.stringify(publish)}\n`,
      changed: true,
    };
  }

  let sectionEnd = buildIndex + 1;
  while (sectionEnd < lines.length) {
    if (/^\s*\[[^\]]+\]\s*(?:#.*)?$/.test(lines[sectionEnd]!)) {
      break;
    }
    sectionEnd++;
  }

  const publishLine = `  publish = ${JSON.stringify(publish)}`;
  const publishPattern = /^\s*publish\s*=\s*(['"]?)([^'"\n#]*)\1?\s*(?:#.*)?$/;

  for (let index = buildIndex + 1; index < sectionEnd; index++) {
    const match = publishPattern.exec(lines[index]!);
    if (!match) {
      continue;
    }

    const previousPublish = match[2]?.trim();
    if (previousPublish === publish) {
      return { content, changed: false, previousPublish };
    }

    lines[index] = publishLine;
    return { content: lines.join("\n"), changed: true, previousPublish };
  }

  lines.splice(buildIndex + 1, 0, publishLine);
  return { content: lines.join("\n"), changed: true };
}

function getGeneratorString() {
  const require = createRequire(import.meta.url);
  const packageJsonPath = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "../package.json",
  );
  const { version } = require(packageJsonPath) as { version: string };
  return `nlite@${version}`;
}

async function exists(filePath: string) {
  const [_, error] = await tryCatch(fs.access(filePath));
  if (error) {
    return false;
  }
  return true;
}
