import { existsSync, readFileSync, statSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { NOT_FOUND_RSC_FILE, STALE_TIME_HEADER } from "./constants.js";

const GENERATED_MARKER = "# Generated by nlite for assets";

export interface HeaderRule {
  pattern: string;
  match: (pathname: string) => boolean;
  headers: Record<string, string>;
}

export function parseHeadersFile(content: string): HeaderRule[] {
  const rules: HeaderRule[] = [];
  let current: HeaderRule | null = null;

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    if (!line.startsWith(" ")) {
      current = {
        pattern: trimmed,
        match: createPathMatcher(trimmed),
        headers: {},
      };
      rules.push(current);
      continue;
    }

    if (!current) {
      continue;
    }

    const colonIndex = trimmed.indexOf(":");
    if (colonIndex === -1) {
      continue;
    }

    const name = trimmed.slice(0, colonIndex).trim();
    const value = trimmed.slice(colonIndex + 1).trim();
    current.headers[name] = value;
  }

  return rules;
}

export function resolveHeadersForPath(rules: HeaderRule[], pathname: string) {
  const headers: Record<string, string> = {};

  for (const rule of rules) {
    if (rule.match(pathname)) {
      Object.assign(headers, rule.headers);
    }
  }

  return headers;
}

export function createPreviewHeadersMiddleware(distDir: string) {
  const headersPath = path.join(distDir, "_headers");
  let cache: { mtimeMs: number; rules: HeaderRule[] } | undefined;

  const getRules = () => {
    if (!existsSync(headersPath)) {
      return [];
    }

    const { mtimeMs } = statSync(headersPath);
    if (cache?.mtimeMs === mtimeMs) {
      return cache.rules;
    }

    const rules = parseHeadersFile(readFileSync(headersPath, "utf8"));
    cache = { mtimeMs, rules };
    return rules;
  };

  return (
    req: import("node:http").IncomingMessage,
    res: import("node:http").ServerResponse,
    next: () => void,
  ) => {
    const rawPathname = req.url?.split("?")[0];
    if (!rawPathname) {
      next();
      return;
    }

    let pathname = rawPathname;
    try {
      pathname = decodeURIComponent(rawPathname);
    } catch {}

    const headers = resolveHeadersForPath(getRules(), pathname);
    for (const [name, value] of Object.entries(headers)) {
      res.setHeader(name, value);
    }

    next();
  };
}

function createPathMatcher(pattern: string) {
  if (pattern === "/*") {
    return () => true;
  }

  const splatIndex = pattern.indexOf("*");
  if (splatIndex === -1) {
    return (pathname: string) => pathname === pattern;
  }

  const prefix = pattern.slice(0, splatIndex);
  const suffix = pattern.slice(splatIndex + 1);

  return (pathname: string) => {
    if (!pathname.startsWith(prefix) || !pathname.endsWith(suffix)) {
      return false;
    }

    return pathname.length >= prefix.length + suffix.length;
  };
}

export async function writeAssetHeaders(
  outDir: string,
  staleTimes: { static: number; dynamic: number },
) {
  const generated = buildRscHeadersContent(staleTimes);
  const headersPath = path.join(outDir, "_headers");

  if (!existsSync(headersPath)) {
    await writeFile(headersPath, generated);
    return;
  }

  const existing = await readFile(headersPath, "utf8");
  const withoutGenerated = stripGeneratedSection(existing);

  await writeFile(
    headersPath,
    withoutGenerated ? `${withoutGenerated.trimEnd()}\n\n${generated}` : generated,
  );
}

function buildRscHeadersContent(staleTimes: { static: number; dynamic: number }) {
  return [
    GENERATED_MARKER,
    "",
    "/*.rsc",
    `  ${STALE_TIME_HEADER}: ${staleTimes.static}`,
    "",
    `/${NOT_FOUND_RSC_FILE}`,
    `  ${STALE_TIME_HEADER}: ${staleTimes.dynamic}`,
    "",
  ].join("\n");
}

function stripGeneratedSection(content: string) {
  const markerIndex = content.indexOf(GENERATED_MARKER);

  if (markerIndex === -1) {
    return content;
  }

  return content.slice(0, markerIndex).trimEnd();
}
