import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { NOT_FOUND_RSC_FILE, STALE_TIME_HEADER } from "./constants.js";

const GENERATED_MARKER = "# Generated by nlite for assets";

export async function writeAssetHeaders(
  outDir: string,
  staleTimes: { static: number; dynamic: number },
) {
  const generated = buildRscHeadersContent(staleTimes);
  const headersPath = path.join(outDir, "_headers");

  if (!existsSync(headersPath)) {
    await writeFile(headersPath, generated);
    return;
  }

  const existing = await readFile(headersPath, "utf8");
  const withoutGenerated = stripGeneratedSection(existing);

  await writeFile(
    headersPath,
    withoutGenerated ? `${withoutGenerated.trimEnd()}\n\n${generated}` : generated,
  );
}

function buildRscHeadersContent(staleTimes: { static: number; dynamic: number }) {
  return [
    GENERATED_MARKER,
    "",
    "/*.rsc",
    `  ${STALE_TIME_HEADER}: ${staleTimes.static}`,
    "",
    `/${NOT_FOUND_RSC_FILE}`,
    `  ${STALE_TIME_HEADER}: ${staleTimes.dynamic}`,
    "",
  ].join("\n");
}

function stripGeneratedSection(content: string) {
  const markerIndex = content.indexOf(GENERATED_MARKER);

  if (markerIndex === -1) {
    return content;
  }

  return content.slice(0, markerIndex).trimEnd();
}
