import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { STALE_TIME_HEADER } from "./constants.js";

const GENERATED_MARKER = "# Generated by nlite for assets";

export async function writeAssetHeaders(outDir: string, staticStaleTimeSeconds: number) {
  const generated = buildRscHeadersContent(staticStaleTimeSeconds);
  const headersPath = path.join(outDir, "_headers");

  if (!existsSync(headersPath)) {
    await writeFile(headersPath, generated);
    return;
  }

  const existing = await readFile(headersPath, "utf8");
  const withoutGenerated = stripGeneratedSection(existing);

  await writeFile(
    headersPath,
    withoutGenerated ? `${withoutGenerated.trimEnd()}\n\n${generated}` : generated,
  );
}

function buildRscHeadersContent(staticStaleTimeSeconds: number) {
  return [
    GENERATED_MARKER,
    "",
    "/*.rsc",
    `  ${STALE_TIME_HEADER}: ${staticStaleTimeSeconds}`,
    "",
  ].join("\n");
}

function stripGeneratedSection(content: string) {
  const markerIndex = content.indexOf(GENERATED_MARKER);

  if (markerIndex === -1) {
    return content;
  }

  return content.slice(0, markerIndex).trimEnd();
}
